language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - rustup target add wasm32-unknown-unknown
  - cargo install -f wasm-bindgen-cli
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - make